import assert from 'node:assert/strict';
import test from 'node:test';
import {prototype} from './prototype-harness.mjs';
import {readyServices,deployService} from './service-fixtures.mjs';

test('缺少服务明确阻塞新增连接，前往统一项目部署',()=>{const p=prototype();p.run('S.projects=S.projects.filter(p=>!p.frpService);');p.click('frp-nodeedit');assert.match(p.html('modal'),/尚无可用服务/);assert.match(p.html('modal'),/data-action="newproject"/);p.submit('frp-nodeedit',{'fn-provider':'s1','fn-server':'s2'});assert.match(p.document.getElementById('modal-error').textContent,/服务实例/);});
test('选择器按服务 ID 显示服务器和运行事实，纯程序准备不在选项',()=>{const p=readyServices();p.click('frp-nodeedit');assert.match(p.html('modal'),/value="frp-n3-client"/);assert.doesNotMatch(p.html('modal'),/value="frp-installed-s1-client"/);p.run('pr("frp-n3-client").runtime="stopped";');p.click('closemodal');p.click('frp-nodeedit');assert.match(p.html('modal'),/已停止/);});
test('确认时服务失效拒绝保存，绑定不按名称匹配',()=>{const p=readyServices(),count=p.run('S.frp.nodes.length');p.click('frp-nodeedit');p.run('S.projects=S.projects.filter(p=>p.id!=="frp-n1-client");');p.submit('frp-nodeedit',{'fn-provider':'frp-n1-client','fn-server':'frp-installed-s2-server'});assert.equal(p.run('S.frp.nodes.length'),count);assert.match(p.document.getElementById('modal-error').textContent,/已部署/);});
test('服务器 / 共享 FRPS 从完整应用参照读取，不伪造第二个服务',()=>{const p=readyServices();assert.equal(p.run('frpBoundService(frpNode("n1"),"server").id===frpBoundService(frpNode("n3"),"server").id'),true);assert.equal(p.run('S.projects.filter(p=>p.frpService?.role==="server"&&p.server==="s2").length'),1);});
test('新增连接只保存绑定，重复关系或监听冲突原子拒绝',()=>{const p=readyServices(),count=p.run('S.frp.nodes.length');p.click('frp-nodeedit');p.submit('frp-nodeedit',{'fn-provider':'frp-n1-client','fn-server':'frp-installed-s2-server'});assert.equal(p.run('S.frp.nodes.length'),count);assert.match(p.document.getElementById('modal-error').textContent,/已存在连接/);const before=p.run('JSON.stringify(frpNode("n1"))');p.click('frp-proxyedit',{node:'n1'});p.submit('frp-proxyedit',{'fp-name':'qa-conflict','fp-type':'tcp','fp-localip':'127.0.0.1','fp-localport':'80','fp-remote':'7000'});assert.equal(p.run('JSON.stringify(frpNode("n1"))'),before);});
test('FRP 在途应用冲突保护共享 FRPS，刷新保留固定目标',()=>{const p=readyServices();p.click('frp-configapply',{node:'n3'});p.submit('frpconfigapply',{'fc-confirm':'on','fc-hold':'on',outcome:'success'});const id=p.run('S.operations[0].id');p.click('frp-configapply',{node:'n1'});p.submit('frpconfigapply',{'fc-confirm':'on','fc-hold':'on',outcome:'success'});assert.match(p.document.getElementById('modal-error').textContent,/冲突/);const q=prototype(p.saved());assert.equal(q.run(`S.operations.find(o=>o.id===${JSON.stringify(id)}).status`),'unknown');assert.equal(q.run(`S.operations.find(o=>o.id===${JSON.stringify(id)}).input.serviceIds.length`),3);});
test('预览后配置修订改变拒绝应用，受理后新编辑不改变固定输入',()=>{const p=readyServices();p.click('frp-configapply',{node:'n3'});p.run('frpNode("n3").revision++;');p.submit('frpconfigapply',{'fc-confirm':'on',outcome:'success'});assert.match(p.document.getElementById('modal-error').textContent,/变化/);p.click('closemodal');p.click('frp-configapply',{node:'n3'});p.submit('frpconfigapply',{'fc-confirm':'on','fc-hold':'on',outcome:'success'});p.run('var fixed=JSON.stringify(S.operations[0].input);frpNode("n3").revision++;');assert.equal(p.run('JSON.stringify(S.operations[0].input)===fixed'),true);p.run('finishOperation(S.operations[0],"success");');assert.equal(p.run('frpNode("n3").appliedConfiguration.revision<frpNode("n3").revision'),true);});
