import test from 'node:test';
import assert from 'node:assert/strict';
import { prototype } from './prototype-harness.mjs';
const firewall={ 'fw-server':'s2','fw-direction':'out','fw-protocol':'TCP','fw-port':'8443','fw-address':'192.0.2.7/32','fw-action':'allow','fw-scope':'container','network-ack':'on',outcome:'success'};
const dns={'dns-type':'A','dns-name':'qa-return','dns-content':'192.0.2.123','dns-ttl':'600','dns-proxy':'on','network-ack':'on',outcome:'success'};
test('single server filters are inherited, all requires explicit selection',()=>{
 const a=prototype();a.run("ui.server='s4'");a.click('newproject');assert.equal(a.document.getElementById('np-server').value,'s4');a.click('firewalledit');assert.equal(a.document.getElementById('fw-server').value,'s4');a.run("ui.server='all'");a.click('newproject');assert.equal(a.document.getElementById('np-server').value,'');a.click('firewalledit');assert.equal(a.document.getElementById('fw-server').value,'');
});
test('firewall ownership cannot change in form or result handler',()=>{
 const a=prototype();a.run("S.firewalls.push({id:'qa-fw',server:'s1',direction:'in',protocol:'TCP',port:'443',address:'192.0.2.0/24',action:'allow',scope:'host',projects:[],protected:false})");a.click('firewalledit',{id:'qa-fw'});assert.ok(a.document.getElementById('fw-server').disabled);a.submit('firewalledit',firewall);assert.equal(a.run("S.operations.filter(o=>o.status==='running').length"),0);assert.throws(()=>a.run("applyNetwork({netType:'firewall',action:'upsert',targetId:'qa-fw',record:{id:'qa-fw',server:'s2'}})"));
});
test('unknown host cannot start firewall mutation',()=>{
 const a=prototype();a.run("networkOperation('firewall','upsert',{id:'qa-host',server:'s3',projects:[],protocol:'TCP',port:'8443'},'success')");assert.equal(a.run("S.operations[0].status"),'rejected');assert.equal(a.run("S.firewalls.some(r=>r.id==='qa-host')"),false);
});
test('DNS confirmation returns exact nonsecret draft and full summary',()=>{
 const a=prototype();a.click('dnsedit');const target=a.run('clone(ui.modal.expectedTarget)');a.submit('dnsedit',{...dns,'dns-account':target.accountId,'dns-zone':target.zoneId});assert.match(a.html('modal'),/代理状态/);assert.match(a.html('modal'),/返回修改/);a.click('dns-back-edit');assert.equal(a.document.getElementById('dns-name').value,'qa-return');assert.equal(a.document.getElementById('dns-content').value,'192.0.2.123');assert.equal(a.document.getElementById('dns-ttl').value,'600');assert.ok(a.document.querySelector('[name=dns-proxy]').checked);assert.equal(a.run('S.operations.length'),prototype().run('S.operations.length'));
});
test('Cloudflare check back preserves name but never token',()=>{
 const a=prototype();a.click('cfconnect');a.submit('cfcheck',{'cf-name':'QA 自定义连接','cf-target':'cf-account-extra','cf-profile':'normal','cf-token':a.run('CF_DEMO_TOKEN')});a.flushTimers();a.click('cf-back-edit');assert.equal(a.document.getElementById('cf-name').value,'QA 自定义连接');assert.equal(a.document.getElementById('cf-token').value,'');
});
test('deployment preview includes actual raw body and adaptation',()=>{
 const a=prototype();a.click('newproject');a.submit('newproject',{'np-template':'t1','np-server':'s4','np-name':'qa-new-project'});assert.match(a.html('modal'),/实际交付正文/);assert.match(a.html('modal'),/复制为此项目配置/);
});
test('generic deployment excludes FRP and provides dedicated entry',()=>{
 const a=prototype();a.click('newproject');assert.doesNotMatch(a.html('modal'),/<option[^>]*value="frp-template-/);assert.match(a.html('modal'),/FRP 专用/);
});

test('firewall copy confirmation is complete and fixed, original preserved',()=>{
 const a=prototype();a.run("S.firewalls.push({id:'qa-copy',server:'s1',direction:'in',protocol:'TCP',port:'443',address:'192.0.2.0/24',action:'allow',scope:'host',projects:['p1'],protected:false});var original=JSON.stringify(S.firewalls.find(r=>r.id==='qa-copy'))");a.click('firewallcopy',{id:'qa-copy'});assert.equal(a.document.getElementById('fw-server').value,'');a.submit('firewalledit',firewall);const id=a.run('ui.modal.record.id');assert.notEqual(id,'qa-copy');for(const label of ['服务器','方向','协议','端口 / 范围','地址 / CIDR','处理动作','作用范围','关联项目'])assert.match(a.html('modal'),new RegExp(label));a.run("ui.server='s1'");a.submit('firewallcommit',{'fw-confirm':'on'});assert.equal(a.run('S.operations[0].input.serverTarget.id'),'s2');a.run('finishOperation(S.operations[0],"success")');assert.equal(a.run("S.firewalls.find(r=>r.id==='"+id+"').server"),'s2');assert.equal(a.run("JSON.stringify(S.firewalls.find(r=>r.id==='qa-copy'))"),a.run('original'));
});
test('FRP installation, shared FRPS, connection and visitor locate by stable identity',()=>{
 const a=prototype();a.click('project',{id:'frp-installed-s1-client'});assert.match(a.html('app'),/不适用 · 独立安装角色/);assert.doesNotMatch(a.html('app'),/当前项目草稿/);a.click('frp-locate',{project:'frp-installed-s1-client'});assert.equal(a.run('ui.modal.kind'),'frp-role-manage');assert.equal(a.run('ui.modal.server'),'s1');a.click('closemodal');a.click('frp-locate',{project:'frp-installed-s2-server'});assert.equal(a.run('ui.modal.role'),'server');a.click('closemodal');a.click('frp-locate',{project:'frp-n1-client'});assert.equal(a.run('FRP.node'),'n1');assert.equal(a.run('FRP.role'),'client');a.click('frp-locate',{project:'frp-n3-visitor'});assert.equal(a.run('FRP.role'),'visitor');a.click('frp-locate',{node:'deleted'});assert.equal(a.run('ui.modal.kind'),'frp-invalid-link');
});
test('project adaptation preserves fixed server/name and public configuration',()=>{
 const a=prototype();const before=a.run('JSON.stringify(S.templates)');a.click('newproject');a.submit('newproject',{'np-template':'t1','np-server':'s4','np-name':'qa-adapt'});a.click('deployment-adapt');const body='[Service]\nExecStart=/srv/qa-adapt/catalog-api\n';a.submit('deploymentadapt',{'adapt-body':body,'adapt-port':'9443','adapt-path-0':'/srv/qa-adapt/catalog-service','adapt-path-1':'/srv/qa-adapt/app.conf'});assert.equal(a.run('ui.modal.kind'),'deploymentpreview');assert.equal(a.run('ui.modal.draft.cfg.source'),body);assert.equal(a.run('ui.modal.draft.server'),'s4');assert.equal(a.run('ui.modal.draft.name'),'qa-adapt');assert.equal(a.run('JSON.stringify(S.templates)'),before);a.click('deployment-preview-back');assert.equal(a.document.getElementById('np-name').value,'qa-adapt');a.submit('newproject',{'np-template':'t1','np-server':'s4','np-name':'qa-adapt'});assert.equal(a.run('ui.modal.draft.cfg.source'),body);
});
test('hash history restores page/object/tab/filter; invalid references are safe',()=>{
 const a=prototype();a.click('navigate',{page:'frp'});a.click('frp-node',{id:'n3'});a.click('navigate',{page:'dns'});a.back();assert.equal(a.run('ui.page'),'frp');assert.equal(a.run('FRP.node'),'n3');assert.equal(a.run('FRP.tab'),'node');a.forward();assert.equal(a.run('ui.page'),'dns');a.click('project',{id:'p1'});a.click('tab',{id:'config'});const hash=a.run('location.hash');assert.match(hash,/project=p1/);const b=prototype(a.saved(),{hash});assert.equal(b.run('ui.tab'),'config');const missing=prototype(a.saved(),{hash:'#frp?tab=files&node=deleted&token=secret'});assert.match(missing.html('app'),/FRP 连接关联失效/);assert.doesNotMatch(missing.run('location.hash'),/secret|token/);assert.equal(a.history().length,new Set(a.history()).size);
});
test('closed DNS and CF forms restore nonsecret inputs after refresh; migration is idempotent',()=>{
 const a=prototype();a.click('dnsedit');const t=a.run('ui.modal.expectedTarget');a.submit('dnsedit',{...dns,'dns-account':t.accountId,'dns-zone':t.zoneId});a.click('closemodal');const b=prototype(a.saved());b.click('dnsedit');assert.equal(b.document.getElementById('dns-name').value,'qa-return');b.click('closemodal');b.click('cfconnect');b.submit('cfcheck',{'cf-name':'QA return','cf-target':'cf-account-extra','cf-profile':'network','cf-token':'DO_NOT_STORE_QA_INPUT'});assert.doesNotMatch(b.saved(),/DO_NOT_STORE_QA_INPUT/);b.click('closemodal');const c=prototype(b.saved());c.click('cfconnect');assert.equal(c.document.getElementById('cf-name').value,'QA return');assert.equal(c.document.getElementById('cf-token').value,'');c.click('closemodal');assert.deepEqual(JSON.parse(prototype(c.saved()).saved()),JSON.parse(c.saved()));
});
test('offline and unchecked targets block all host lines; DNS remains independent',()=>{
 const a=prototype();a.run("sr('s1').state='offline';sr('s2').state='unknown'");a.run("startOperation(pr('p1'),'restart',{},'success',{hold:true})");assert.equal(a.run('S.operations[0].status'),'rejected');a.run("frpRunInstallation(frpInstallationPlan('s2','server'),{identity:true,impact:true,hold:true})");assert.equal(a.run('S.operations[0].status'),'rejected');a.run("networkOperation('firewall','upsert',{id:'qa-offline',server:'s1',projects:[],protocol:'TCP',port:'8443'},'success')");assert.equal(a.run('S.operations[0].status'),'rejected');a.click('dnsedit');const t=a.run('ui.modal.expectedTarget');a.submit('dnsedit',{...dns,'dns-account':t.accountId,'dns-zone':t.zoneId});a.submit('dnscommit',{'dns-confirm':'on'});assert.equal(a.run('S.operations[0].status'),'running');a.run('finishOperation(S.operations[0],"success")');assert.equal(a.run('S.operations[0].status'),'success');
});
test('new firewall draft keeps inputs but inherits a newly selected target',()=>{
 const a=prototype();a.run("ui.server='s1'");a.click('firewalledit');a.submit('firewalledit',{...firewall,'fw-server':'s1'});a.click('closemodal');a.run("ui.server='s4'");a.click('firewalledit');assert.equal(a.document.getElementById('fw-server').value,'s4');assert.equal(a.document.getElementById('fw-port').value,'8443');a.click('closemodal');a.run("ui.server='all'");a.click('firewalledit');assert.equal(a.document.getElementById('fw-server').value,'');
});
test('DNS confirmation does not overwrite a record changed while waiting',()=>{
 const a=prototype();a.click('dnsedit',{id:'dns1'});a.submit('dnsedit',dns);a.run('S.dns.find(r=>r.id==="dns1").content="192.0.2.201";S.cloudflare.recordVersions.dns1++');a.submit('dnscommit',{'dns-confirm':'on'});assert.match(a.document.getElementById('modal-error').textContent,/记录在确认后变化/);assert.equal(a.run('S.operations.some(o=>o.status==="running")'),false);assert.equal(a.run('S.dns.find(r=>r.id==="dns1").content'),'192.0.2.201');
});
test('stale credential draft requires explicit recheck and preserves input',()=>{
 const a=prototype();a.click('dnsedit',{id:'dns1'});a.submit('dnsedit',dns);a.click('closemodal');a.run('const credential=cfCredential(cfCurrent("cf-account-legacy"));cfCurrent("cf-account-legacy").credentialRevision++;credential.revision++');a.click('dnsedit',{id:'dns1'});assert.match(a.html('modal'),/重新核对当前目标/);const rev=a.run('ui.modal.expectedTarget.credentialRevision');a.click('dns-refresh-target');assert.equal(a.run('ui.modal.expectedTarget.credentialRevision'),rev+1);assert.equal(a.document.getElementById('dns-name').value,'qa-return');
});
test('known occupied paths block; old text alone does not imply a conflict',()=>{
 const a=prototype();a.run('const template=tpl("t1"),draft=newProjectDraft(template,sr("s2"),"qa-conflict");draft.cfg.port=9443;');assert.ok(a.run('deploymentLocation(draft).errors.some(e=>e.includes("目标路径已由"))'));a.run('draft.server="s4";draft.cfg.fileMappings.forEach((m,i)=>m.targetPath="/srv/qa-safe/file"+i)');assert.equal(a.run('deploymentLocation(draft).errors.length'),0);assert.match(a.run('configText(draft)'),/catalog-api/);
});
test('installation apply uses adopted draft, never silently follows public program',()=>{
 const a=prototype();const pins=a.run('JSON.stringify(pr("frp-installed-s1-client").frpDraft.programRef)');a.run('tpl("frp-template-client").programRef.pins=[];S.frp.settingsRev++;frpSyncConfigs();');a.click('frp-project-apply',{id:'frp-installed-s1-client'});assert.equal(a.run('JSON.stringify(ui.modal.plan.programRef)'),pins);assert.equal(a.run('ui.modal.plan.sourceDraft.projectId'),'frp-installed-s1-client');assert.equal(a.run('ui.modal.plan.files.toml'),'');assert.equal(a.run('S.programs.filter(f=>f.id.startsWith("frp-bin-")).every(f=>f.bytes===0&&f.placeholder)'),true);
});
