import assert from 'node:assert/strict';
import test from 'node:test';
import {prototype} from './prototype-harness.mjs';
function preview(p,name='qa-service',server='s4'){p.click('newproject',{template:'t1',server});p.submit('newproject',{'np-template':'t1','np-server':server,'np-name':name});}

test('普通部署表单只含三个主要输入，全部视图明确选择目标',()=>{const p=prototype();p.click('newproject');assert.deepEqual([...p.html('modal').matchAll(/name="(np-[^"]+)"/g)].map(m=>m[1]),['np-template','np-server','np-name']);assert.equal(p.document.getElementById('np-server').value,'');});
test('部署输入固定在操作中，成功后才建立项目，期间切换筛选不改目标',()=>{const p=prototype(),count=p.run('S.projects.length');preview(p);p.click('deployment-preview-execute');assert.equal(p.run('S.projects.length'),count);assert.equal(p.run('S.operations[0].input.deployment.project.server'),'s4');p.run('ui.server="s1";finishOperation(S.operations[0],"success");');assert.equal(p.run('S.projects.find(p=>p.name==="qa-service").server'),'s4');});
test('无效主机不能创建操作或项目',()=>{const p=prototype(),count=p.run('S.operations.length');preview(p,'qa-blocked','s3');p.click('deployment-preview-execute');assert.equal(p.run('S.operations.length'),count);assert.equal(p.run('S.projects.some(p=>p.name==="qa-blocked")'),false);});
test('部署刷新中断转换为未知操作与恢复记录',()=>{const p=prototype();preview(p);p.click('deployment-preview-execute');const q=prototype(p.saved());assert.equal(q.run('S.operations[0].status'),'unknown');assert.equal(q.run('S.projects.some(p=>p.name==="qa-service")'),false);assert.equal(q.run('S.failedProjects[0].deployment.project.name'),'qa-service');});
test('同机部署名唯一，取消预览不预占名称，旧卸载名不保留为实体',()=>{const p=prototype();preview(p,'catalog-api','s2');assert.match(p.document.getElementById('modal-error').textContent,/同名/);preview(p,'catalog-api','s4');assert.equal(p.run('ui.modal.kind'),'deploymentpreview');p.click('closemodal');preview(p,'catalog-api','s4');assert.equal(p.run('ui.modal.kind'),'deploymentpreview');preview(p,'legacy-web','s4');assert.equal(p.run('ui.modal.kind'),'deploymentpreview');});
test('非法项目名不创建操作，成功项目仍可停止并保留实体',()=>{const p=prototype();preview(p,'1 invalid');assert.match(p.document.getElementById('modal-error').textContent,/英文字母/);preview(p);p.click('deployment-preview-execute');p.run('finishOperation(S.operations[0],"success");const p=S.projects.find(p=>p.name==="qa-service"),op=startOperation(p,"stop",{},"success",{hold:true});finishOperation(op,"success");');assert.equal(p.run('S.projects.find(p=>p.name==="qa-service").runtime'),'stopped');});
test('部署未受理不预占名，正在执行时同名资源受保护',()=>{const p=prototype();preview(p);p.click('deployment-preview-execute');const id=p.run('S.operations[0].id');preview(p);p.click('deployment-preview-execute');assert.equal(p.run('S.operations[0].status'),'rejected');assert.equal(p.run(`S.operations.find(o=>o.id===${JSON.stringify(id)}).status`),'running');assert.equal(p.run('S.projects.some(p=>p.name==="qa-service")'),false);});
